name: Testkube on vCluster
on:
  pull_request:
    branches:
      - main

jobs:
  run-test:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
     
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_ZONE }}

      - name: Install vCluster CLI
        run: |
          curl -sSL https://github.com/loft-sh/vcluster/releases/latest/download/vcluster-linux-amd64 -o vcluster
          chmod +x vcluster
          sudo mv vcluster /usr/local/bin

      - name: Set env
        run: |
          echo "PR_NUMBER=${{ github.event.number }}" >> $GITHUB_ENV

      - name: Create vCluster
        run: |
          echo "Running for PR ${{ env.PR_NUMBER }}"
          vcluster create testkube-vcluster-${{ env.PR_NUMBER }} --namespace demo-${{ env.PR_NUMBER }} --connect=false
          echo "Waiting for vCluster to be ready..."
          sleep 100

      - name: Connect to vCluster
        run: |
          vcluster connect testkube-vcluster-${{ env.PR_NUMBER }} --namespace demo-${{ env.PR_NUMBER }}
          kubectl config current-context  # verify vcluster context is active
          echo "Show pods on vCluster"
          kubectl get pods -n demo-${{ env.PR_NUMBER }}

      - name: Deploy Sample Application
        run: |
          kubectl apply -f nginx-deployment.yaml
          kubectl get all

      - name: Setup Testkube
        uses: kubeshop/setup-testkube@v1
        with:
          organization: ${{ secrets.TESTKUBE_ORG_ID }}
          environment: ${{ secrets.TESTKUBE_ENV_ID }}
          token: ${{ secrets.TESTKUBE_API_TOKEN }}

      - name: Provision ephemeral runner
        run: |
          testkube install runner github-action-runner-${{ github.run_id }} --create --env sonali-srivastava-personal-env --namespace testkube --floating

      - name: Run Test
        run: |
           testkube run testworkflow curl-nginx-app \
           -f \
           --config url=http://nginx-service.default.svc.cluster.local \
           --target name=github-action-runner-${{ github.run_id }} \
           --tag pull-request=PR-${{ github.run_id }}

      - name: Disconnect vCluster and delete resources
        run: |
          testkube delete runner github-action-runner-${{ github.run_id }} --delete --uninstall
          vcluster disconnect
          kubectl delete ns demo-${{ env.PR_NUMBER }}
